services:
  php1:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php1
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - app-net
    env_file:
      - ./src/Config/.env

  php2:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php2
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - app-net
    env_file:
      - ./src/Config/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php1
    networks:
      - app-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TesteFinch@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'TesteFinch@123' -Q 'SELECT 1' > /dev/null; do sleep 2; done"]
      interval: 10s
      timeout: 5s
      retries: 10

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./src/public:/usr/share/nginx/html/docs
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
