services:
  php1:
    build: ./docker/php
    container_name: php1
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - app-net
    env_file:
      - ./src/Config/.env

  php2:
    build: ./docker/php
    container_name: php2
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - app-net
    env_file:
      - ./src/Config/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php1
    networks:
      - app-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TesteFinch@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1433"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  app-net:
    driver: bridge
